language: node_js
node_js:
  - 12
before_install:
  - mkdir -p shogi/boards
  - touch shogi/boards/temp.sqlite3
after_install:
  - sed -i 's/:$/;/g' node_modules/Cloudstorm/index.d.ts
script:
  # Typecheck files not covered by tests
  - tsc --noEmit
  - npm test
  - npx codecov
