name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Before Install
        run: |
          mkdir -p shogi/boards
          touch shogi/boards/temp.sqlite3

      - run: npm ci

      - name: Before Script
        run: |
          sed -i 's/:$/;/g' node_modules/Cloudstorm/index.d.ts

      - name: Typecheck files not covered by tests
        run: npx tsc --noEmit

      - name: Test
        run: npm test

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed "s/\/.\+//g" CODEOWNERS | grep "^[a-z]" | xargs -n 1 -I {} sh -c "eslint --ext js,ts -f rdjson {} | reviewdog -f=rdjson -reporter=github-pr-review"

      - name: Lint
        run: npm run lint
        continue-on-error: true

      - name: codecov
        run: npx codecov
